services:
  - type: web
    name: finanzas-personales
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn finanzas_personales.wsgi:application --log-file - --log-level debug
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.12.3
