services:
  - type: web
    name: finanzas-personales
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn finanzas_personales.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.12.3
