# Generated by Django 5.2.2 on 2025-06-07 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumodiario',
            name='consumo_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_relacionadas', to='core.consumodiario'),
        ),
        migrations.AlterField(
            model_name='consumodiario',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
        migrations.AlterField(
            model_name='consumodiario',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consumodiario',
            name='fecha',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='consumodiario',
            name='tipo_pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipopago'),
        ),
    ]
