# Generated by Django 5.2.2 on 2026-01-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_consumodiario_consumo_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='icono',
            field=models.CharField(default='fa-solid fa-tag', help_text='Clase de Font Awesome para el icono', max_length=50),
        ),
    ]
