# Generated by Django 5.2.2 on 2026-01-03 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_categoria_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumofijomensual',
            name='tipo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_fijos', to='core.tipopago'),
        ),
    ]
