# Generated by Django 5.2.2 on 2026-01-03 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_consumofijomensual_tipo_pago'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='consumofijomensual',
            unique_together=set(),
        ),
    ]
