# Generated by Django 5.2.2 on 2026-01-03 21:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_consumofijomensual_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_cuotas', models.IntegerField()),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now, help_text='Fecha de la primera cuota')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='core.categoria')),
                ('tipo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos', to='core.tipopago')),
            ],
            options={
                'verbose_name': 'Crédito',
                'verbose_name_plural': 'Créditos',
            },
        ),
        migrations.AddField(
            model_name='consumofijomensual',
            name='credito_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_generadas', to='core.credito'),
        ),
    ]
