# Generated by Django 5.2.2 on 2026-01-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_credito_consumofijomensual_credito_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumodiario',
            name='cuota_numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='consumodiario',
            name='cuota_total',
            field=models.IntegerField(default=1),
        ),
    ]
