# Generated by Django 5.2.2 on 2026-01-05 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_consumodiario_cuota_numero_consumodiario_cuota_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumodiario',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentario específico para este mes', null=True),
        ),
        migrations.AddField(
            model_name='consumofijomensual',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentario específico para este mes', null=True),
        ),
    ]
