# Generated by Django 5.2.2 on 2026-01-05 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_consumodiario_comentario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumodiario',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumodiario',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
