# Generated by Django 5.2.2 on 2026-01-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_consumodiario_fecha_pago_consumodiario_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumodiario',
            name='primera_cuota_siguiente_mes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tipopago',
            name='es_tarjeta_debito',
            field=models.BooleanField(default=False),
        ),
    ]
